
services:
  fastapi:
    build: .
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    develop:
      watch:
        - path: .
          action: rebuild


  postgres:
    image: postgres:15-alpine
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 3




volumes:
  postgres_data:

